language: go

go:
- "1.11"

script:
  - export GO111MODULE=on
  - go test -coverprofile=coverage.out ./pkg/trie/...
  - cat coverage.out | grep -v "trie_search.go" > coverage.out


after_success:
  - bash <(curl -s https://codecov.io/bash)
