language: go

go:
- "1.11"

script:
  - export GO111MODULE=on
  - go test -coverprofile=coverage.out.tmp ./pkg/...
  - touch coverage.out
  - cat coverage.out.tmp | grep -v "trie_search.go" > coverage.out
  - rm coverage.out.tmp


after_success:
  - bash <(curl -s https://codecov.io/bash)
